# Generated by Django 5.1.7 on 2025-03-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_category_product_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image2',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image3',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
