# Generated by Django 5.1.7 on 2025-03-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_testimonial_options_testimonial_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
