# Generated by Django 5.2 on 2025-04-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_wishlistitem_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes about this order (not visible to customers)', null=True),
        ),
    ]
